"""added price column to the baked_goods table

Revision ID: 60821af2902d
Revises: 0f4954cacff0
Create Date: 2023-09-20 19:48:44.911630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60821af2902d'
down_revision = '0f4954cacff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baked_goods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baked_goods', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
